meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlansListView,
    MealPlansCreateView,
    MealPlansDetailView,
    MealPlansUpdateView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlansListView.as_view(), name="meal_plan_list"),
    path(
        "<int:pk>/",
        MealPlansDetailView.as_view(),
        name="meal_plan_detail",
    ),
    path(
        "create/",
        MealPlansCreateView.as_view(),
        name="meal_plan_new",
    ),
    path(
        "<int:pk>/edit/",
        MealPlansUpdateView.as_view(),
        name="meal_plan_edit",
    ),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


class MealPlans(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(auto_now_add=False)
    owner = models.ForeignKey(
        USER_MODEL, on_delete=models.CASCADE, related_name="ownermeal"
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe",
        related_name="meal_plans",
    )

    def __str__(self):
        return self.name + "by" + str(self.owner)

meal_plans/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plans.models import MealPlans


class MealPlansListView(LoginRequiredMixin, ListView):
    model = MealPlans
    template_name = "mealplans/list.html"
    context_object_name = "mealsplans_list"

    def get_queryset(self):
        return MealPlans.objects.filter(owner=self.request.user)


class MealPlansCreateView(LoginRequiredMixin, CreateView):
    model = MealPlans
    template_name = "mealplans/new.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)

    def get_success_url(self):
        return reverse_lazy("meal_plan_list")


class MealPlansDetailView(LoginRequiredMixin, DetailView):
    name = MealPlans
    template_name = "mealplans/detail.html"
    fields = ["name", "recipes", "date"]
    context_object_name = "mealplansdetail"

    def get_queryset(self):
        return MealPlans.objects.filter(owner=self.request.user)


class MealPlansUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlans
    template_name = "mealplans/edit.html"
    fields = [
        "name",
        "owner",
        "description",
    ]

    def get_queryset(self):
        return MealPlans.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlans
    template_name = "mealplans/delete.html"
    success_url = reverse_lazy("meal_plan_list")

    def get_queryset(self):
        return MealPlans.objects.filter(owner=self.request.user)

meal_plans/templates/mealplans/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>

    </body>
</html>

meal_plans/templates/mealplans/detail.html
{% extends 'base.html' %}


  {% block content %}
    <main class="recipe-detail">


      <h1>{{ mealplans.name }}</h1>
      <h2>{{ mealplans.owner | default_if_none:"Uknown" }}</h2>
      <p>
        Created on {{ mealplans.created }} |
        Updated on {{ mealplans.updated }}
      </p>
      <form method="post" action="{% url 'recipe_rating' recipe.id %}">
        {% csrf_token %}
        <div class="rating-form-grid">
          {{ rating_form.as_p }}
          <button class="button">Rate</button>
        </div>
      </form>

    </main>
  {% endblock content %}

meal_plans/templates/mealplans/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>

    </body>
</html>

meal_plans/templates/mealplans/list.html
{% extends 'base.html' %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  {% endblock pagination %}


  {% block content %}
  <main class="recipe-grid">
    <a href="{% url 'meal_plan_new' %}">Create</a>
    <h1>{{ mealplans.name }}</h1>
    {% for meals in mealplans_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plan_list'  %}">{{ mealplans.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ ownermeal.updated }}</p>
      </div>
    {% endfor %}
  </main>
  {% endblock content %}

meal_plans/templates/mealplans/new.html
{% extends 'base.html' %}

  {% block content %}
    <main class="recipe-form">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
          <button class="button">Create</button>
        </div>
      </form>
    </main>
  {% endblock content %}